/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AutoComplete: typeof import('primevue/autocomplete')['default']
    BuildSection: typeof import('./src/components/BuildSection.vue')['default']
    Button: typeof import('primevue/button')['default']
    CustomBuild: typeof import('./src/components/CustomBuild.vue')['default']
    Divider: typeof import('primevue/divider')['default']
    DownloadImagePanel: typeof import('./src/components/DownloadImagePanel.vue')['default']
    EditPackages: typeof import('./src/components/EditPackages.vue')['default']
    Fieldset: typeof import('primevue/fieldset')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    ImageBuilder: typeof import('./src/components/ImageBuilder.vue')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    LangSelect: typeof import('./src/components/LangSelect.vue')['default']
    Listbox: typeof import('primevue/listbox')['default']
    MainContent: typeof import('./src/components/MainContent.vue')['default']
    Message: typeof import('primevue/message')['default']
    ModelSelector: typeof import('./src/components/ModelSelector.vue')['default']
    Panel: typeof import('primevue/panel')['default']
    Popover: typeof import('primevue/popover')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    Select: typeof import('primevue/select')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
  }
}
