packages: []

catalog: null

catalogs:
  dev:
    '@antfu/eslint-config': ^4.14.1
    '@iconify-json/carbon': ^1.2.9
    '@intlify/eslint-plugin-vue-i18n': ^4.1.0
    '@intlify/unplugin-vue-i18n': ^11.0.1
    '@primevue/auto-import-resolver': ^4.4.1
    '@tsconfig/node24': ^24.0.3
    '@types/jsdom': ^27.0.0
    '@types/node': ^22.15.31
    '@unocss/eslint-plugin': ^66.2.0
    '@vitejs/plugin-vue': ^5.2.4
    '@vue/test-utils': ^2.4.6
    '@vue/tsconfig': ^0.8.1
    eslint: ^9.28.0
    eslint-plugin-format: ^1.0.1
    jsdom: ^26.1.0
    lint-staged: ^16.1.0
    simple-git-hooks: ^2.13.0
    taze: ^19.1.0
    typescript: ^5.8.3
    unocss: ^66.5.9
    unplugin-auto-import: ^19.3.0
    unplugin-vue-components: ^28.7.0
    vite: ^6.3.5
    vitest: ^3.2.3
    vue-tsc: ^2.2.10
  frontend:
    '@primeuix/themes': ^2.0.0
    '@vueuse/core': ^13.3.0
    fuzzysort: ^3.1.0
    primevue: ^4.4.1
    vue: ^3.5.16
    vue-i18n: ^11.2.2

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
